name: default
ros:
  setup: /opt/ros/jazzy/setup.bash
  domain_id: 0
  middleware: rmw_cyclonedds_cpp

paths:
  workspace_root: /workspace
  bags_dir: /workspace/bags
  logs_dir: /workspace/logs
  outputs_dir: /workspace/outputs
  state_dir: /workspace/.state

capture:
  storage_id: mcap
  wait_topics_sec: 15
  include_renderer_topic: false
  launch_renderer: false
  launch_basler: true
  basler_enable_chunk_timestamp: false
  startup_message_check_sec: 2
  event_driver_launch: "ros2 launch /workspace/scripts/metavision_driver_composition_with_bias.launch.py serial:=00051466 erc_mode:=enabled erc_rate:=5000000 bias_file:=/workspace/config/event_camera/my_camera.bias"
  event_renderer_launch: "ros2 launch event_camera_renderer renderer.launch.py"
  basler_launch: "/workspace/scripts/basler_launch_helper.sh --config-file /workspace/config/basler/basler_colour.yaml --camera-id my_camera --startup-user-set CurrentSetting --mtu-size 8192 --enable-status-publisher false --enable-current-params-publisher false"

topics:
  event_packets: /event_camera/events
  event_image: /event_camera/renderer/image_raw
  basler_image: /my_camera/pylon_ros2_camera_node/image_raw
  basler_info: /my_camera/pylon_ros2_camera_node/camera_info

extraction:
  window_ms: 16.66
  image_ext: png
  color_mode: blue-red
  mirror_basler_image: false
  mirror_event_image: true
  crop_basler_image: true
  basler_pixel_pitch_um: 5.3 # 5.3 for aca1300-60gc
  event_pixel_pitch_um: 4.86
  basler_crop_offset_x_px: 7
  basler_crop_offset_y_px: 62
  drop_leading_empty_windows: true
  transparent_bg: true
  skip_empty_windows: false
  max_pairs: 0
  output_subdir: synced_pairs
  raw_events_csv: false
  raw_events_hdf5: false
  event_resolution:
    width: 1280
    height: 720
